language: java
sudo: false
script:
  - mvn spring-boot:run
addons:
  ssh_known_hosts: 139.196.140.110
before_deploy:
  - openssl aes-256-cbc -K $encrypted_383bc2ea2d21_key -iv $encrypted_383bc2ea2d21_iv -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist root@139.196.140.110:/opt
  on:
    branch: master